enum TencentCloudChatComponentsEnum {
  message,
  conversation,
  contact,
  search,
  userProfile,
  groupProfile,
  applicationList,
  applicationDetail,
  groupList,
  blockList,
  friendInfo,
  groupApplicationList,
  settings,
  settingsInfo,
  settingsAbout,
  homepage,
  loginPage
}
